### ISSUE TITLE
patch zip-file download error

### ISSUE THREAD

**Issue by LeoWang** [dpursehouse/pygerrit2#19] opened 2018-04-07 03:58 UTC
I used pygerrit2 for gerrit download zip-file. My gerrit version was 2.14.7, and pygerrit version was 2.0.2.
I write my test code like the example:
`auth = HTTPBasicAuth('_username_', '_password_')`
`rest = GerritRestAPI(url='http://_ip_:_port_', auth=auth)`
`response = rest.get("/changes/_changeid_/revisions/current/patch?zip"`
But it always raise the exception:

response = rest.get("/changes/%s/revisions/current/patch?zip"%(str(change_id)))
  File "/usr/local/lib/python2.7/dist-packages/pygerrit2/rest/__init__.py", line 145, in get
    return _decode_response(response)
  File "/usr/local/lib/python2.7/dist-packages/pygerrit2/rest/__init__.py", line 44, in _decode_response
    content = response.content.strip().decode("UTF-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 10: invalid continuation byte

Please show me tips

**Comment by MartinWallgren** [comment] 2018-06-04 11:52
Unable to reproduce this, I can retrieve patch zip files without issue.

I believe this was fixed in 5fb143c which was part of 2.0.3. The offending call to  `.decode("UTF-8")` was removed in that commit.

**Closed** 2018-06-08 14:15 UTC
