### ISSUE TITLE
403 or errorless failure to post review?

### ISSUE THREAD

**Issue by zephyrmoth** [dpursehouse/pygerrit2#22] opened 2018-05-29 22:07 UTC
I'm at the end of my rope and hoping I can diagnose what this issue is. I'm using Pygerrit2 to attempt to automate code testing and reviews for a project. The GerritRest API works perfectly for pulling JSON objects, and also seems to function correctly in testing scripts for posting reviews. However, more or less the same script fails when integrated into the production script. Depending on how much of the intermediate code I skip, I either receive no errors but fail to post a review, or a 403 error. The latter is particularly odd as my credentials work perfectly fine in test scripts and I have tried making a new auth token before posting reviews.
I do not necessarily know how to reproduce this but I do not grasp how this could be a local issue at this point. Is there some behavior that could be causing a failure that I should check for? Does it interact with other processes in some way that could impact it?

**Comment by dpursehouse** [comment] 2018-06-03 08:44
I'm not sure what's causing this.  I have also just run into something similar while attempting to automate pygerrit tests against Gerrit running in Docker using the `testcontainers` library.

**Comment by dpursehouse** [comment] 2018-06-03 08:55
Actually I just realised that in my case it was because I was authenticating with digest auth instead of basic.  `GET` requests were working OK, but `PUT` and `POST` were failing with `403`.

**Comment by zephyrmoth** [comment] 2018-06-04 14:12
I've still had this issue with basic auth, which is strange. Would being a private change have anything to do with it potentially?

**Comment by dpursehouse** [comment] 2018-06-04 14:15
Maybe, if your user can't see the change.  But then I would expect a "404 not found" result, not a 403.

What version of Gerrit are you using?  I assume at least 2.15 if you're using private changes.

**Comment by zephyrmoth** [comment] 2018-06-04 14:18
Indeed, and these credentials do work so it's odd to get a permissions issue.
In regards to Gerrit we're running 2.15.2.

**Comment by dpursehouse** [comment] 2018-07-06 12:49
Just a thought... are you doing multiple calls with the same API instance and it's working for the first call(s) but then failing on a subsequent one?

**Comment by dpursehouse** [comment] 2019-02-27 07:09
Closing this since I can't reproduce it.  Please reopen if you have more details that could shed light on the problem.

**Closed by dpursehouse** 2019-02-27 07:09 UTC
